#!/usr/bin/env bash
# Writes include/borink/object_storage.h from src/lib.rs.
#
# Run this after changing the ABI, and commit what it writes. CI runs it and
# fails on a diff. docs/PACKAGING.md says why the header is committed rather
# than generated by a build script.
#
#     nix develop --command crates/object-storage-c/generate-header.sh
#
# `flake.nix` pins the cbindgen version. Without nix, install the same one:
# `cargo install cbindgen --version 0.29.4`. Point releases differ in
# whitespace, so a different one fails CI's diff.

set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

cbindgen --quiet \
    --config "$here/cbindgen.toml" \
    --crate borink-object-storage-c \
    --output "$here/include/borink/object_storage.h" \
    "$here"
