[package]
name = "borink-object-storage-no-allocator"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["std"]
link-check = []
std = []

[lib]
crate-type = ["staticlib"]
test = false
doctest = false

[dependencies]
borink-object-storage-proto = { path = "../../crates/object-storage-proto" }

[lints.rust]
missing_docs = "deny"
