[package]
name = "borink-object-storage-proto"
version = "0.0.1"
edition = "2024"
license = "Apache-2.0"
description = "Object storage operations with a sans-IO core and externally buffered API, with support for Azure Blob Storage"
repository = "https://github.com/borink-org/object-storage"
readme = "../../README.md"
rust-version = "1.97.1"
keywords = ["azure", "blob-storage", "object-storage", "sans-io", "no-std"]
categories = ["no-std::no-alloc", "api-bindings", "network-programming"]

[dependencies]

[lints.rust]
missing_docs = "deny"
