// Azure Blob Storage for a program that owns its memory and its I/O.
//
// GENERATED by cbindgen from crates/object-storage-c/src/lib.rs. Do not edit.
// Edit the Rust source and build the crate; CI fails if this file and that
// source disagree.

#ifndef BORINK_OBJECT_STORAGE_H
#define BORINK_OBJECT_STORAGE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * The most headers that one request head carries.
 *
 * This is the core crate's own bound, and the array in `borink_request_head`
 * has exactly this many slots. A compile-time assertion stops the build if
 * the core crate raises it.
 */
#define BORINK_MAX_HEADERS 6

/**
 * Which kind of failure a `borink_status` carries.
 *
 * These are the numbers that the core crate's error code uses.
 */
enum borink_error_code
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Nothing failed.
     */
    BORINK_ERROR_CODE_NONE = 0,
    /**
     * The endpoint is not an ASCII HTTP or HTTPS origin.
     */
    BORINK_ERROR_CODE_INVALID_ENDPOINT = 1,
    /**
     * The container name is not usable in a request.
     */
    BORINK_ERROR_CODE_INVALID_CONTAINER = 2,
    /**
     * The token is not usable as one HTTP header value.
     */
    BORINK_ERROR_CODE_INVALID_TOKEN = 3,
    /**
     * The plan cannot become a request. `detail` says why.
     */
    BORINK_ERROR_CODE_INVALID_PLAN = 4,
    /**
     * The buffer is too small. Grow it to `required` and call again.
     */
    BORINK_ERROR_CODE_CAPACITY = 5,
    /**
     * The response cannot be read. `detail` says which part was wrong.
     */
    BORINK_ERROR_CODE_RESPONSE = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_error_code borink_error_code;
#else
typedef uint16_t borink_error_code;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The HTTP method of a request.
 */
enum borink_method
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * `GET`.
     */
    BORINK_METHOD_GET = 1,
    /**
     * `HEAD`.
     */
    BORINK_METHOD_HEAD = 2,
    /**
     * `PUT`.
     */
    BORINK_METHOD_PUT = 3,
    /**
     * `DELETE`.
     */
    BORINK_METHOD_DELETE = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_method borink_method;
#else
typedef uint16_t borink_method;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a read asks the service to return.
 */
enum borink_get_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The bytes of the object.
     */
    BORINK_GET_KIND_BYTES = 1,
    /**
     * The metadata of the object, without its bytes.
     */
    BORINK_GET_KIND_METADATA = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_get_kind borink_get_kind;
#else
typedef uint16_t borink_get_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which form of byte range a read requests.
 */
enum borink_range_form
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Every byte of the object. `start` and `end` are 0.
     */
    BORINK_RANGE_FORM_WHOLE = 1,
    /**
     * The half-open interval `start..end`.
     */
    BORINK_RANGE_FORM_BOUNDED = 2,
    /**
     * Every byte from `start` to the end of the object.
     */
    BORINK_RANGE_FORM_OFFSET = 3,
    /**
     * The last `start` bytes. Azure Blob Storage refuses this form.
     */
    BORINK_RANGE_FORM_SUFFIX = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_range_form borink_range_form;
#else
typedef uint16_t borink_range_form;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The ETag precondition that a request carries.
 *
 * A request that carries one passes the entity tag as `condition_value`. A
 * request that carries none passes an empty `condition_value`.
 */
enum borink_condition
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The request carries no precondition.
     */
    BORINK_CONDITION_NONE = 1,
    /**
     * The request succeeds only if the current ETag matches.
     */
    BORINK_CONDITION_IF_MATCH = 2,
    /**
     * The request succeeds only if the current ETag differs.
     */
    BORINK_CONDITION_IF_NONE_MATCH = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_condition borink_condition;
#else
typedef uint16_t borink_condition;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a removal takes with it.
 */
enum borink_delete_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Remove the object alone. Azure refuses this if it has snapshots.
     */
    BORINK_DELETE_KIND_OBJECT = 1,
    /**
     * Remove the object and its snapshots.
     */
    BORINK_DELETE_KIND_OBJECT_AND_SNAPSHOTS = 2,
    /**
     * Remove the snapshots and keep the object.
     */
    BORINK_DELETE_KIND_SNAPSHOTS_ONLY = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_delete_kind borink_delete_kind;
#else
typedef uint16_t borink_delete_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The category of a service failure.
 *
 * These are the numbers that the core crate's failure class uses. A number
 * that is not listed here comes from a later version of that crate. It
 * crosses unchanged, never as a substitute.
 */
enum borink_failure_class
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The failure carries no category.
     */
    BORINK_FAILURE_CLASS_NONE = 0,
    /**
     * The service rejected the credentials or the authorization.
     */
    BORINK_FAILURE_CLASS_AUTH = 1,
    /**
     * The service throttled the request. You can retry it later.
     */
    BORINK_FAILURE_CLASS_THROTTLED = 2,
    /**
     * The service failed, or it was unavailable.
     */
    BORINK_FAILURE_CLASS_SERVER = 3,
    /**
     * The service answered with a redirect.
     */
    BORINK_FAILURE_CLASS_REDIRECT = 4,
    /**
     * Any other failure, such as a malformed request.
     */
    BORINK_FAILURE_CLASS_OTHER = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_failure_class borink_failure_class;
#else
typedef uint16_t borink_failure_class;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The specific error that the service named.
 *
 * These are the numbers that the core crate's service error kind uses, and
 * they cross unchanged in both directions.
 */
enum borink_service_error
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The service named no error.
     */
    BORINK_SERVICE_ERROR_NONE = 0,
    /**
     * The object does not exist.
     */
    BORINK_SERVICE_ERROR_NOT_FOUND = 1,
    /**
     * The container does not exist.
     */
    BORINK_SERVICE_ERROR_NO_SUCH_CONTAINER = 2,
    /**
     * The object or the container already exists.
     */
    BORINK_SERVICE_ERROR_ALREADY_EXISTS = 3,
    /**
     * The service rejected the credentials or the authorization.
     */
    BORINK_SERVICE_ERROR_UNAUTHORIZED = 4,
    /**
     * A precondition on the request did not hold.
     */
    BORINK_SERVICE_ERROR_PRECONDITION = 5,
    /**
     * The service cannot serve the requested byte range.
     */
    BORINK_SERVICE_ERROR_RANGE_NOT_SATISFIABLE = 6,
    /**
     * The service throttled the request.
     */
    BORINK_SERVICE_ERROR_THROTTLED = 7,
    /**
     * The service timed out while it processed the request.
     */
    BORINK_SERVICE_ERROR_TIMEOUT = 8,
    /**
     * The service failed, or it was unavailable.
     */
    BORINK_SERVICE_ERROR_SERVICE = 9,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_service_error borink_service_error;
#else
typedef uint16_t borink_service_error;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which outcome a response head became.
 */
enum borink_outcome_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * A body follows. Read it and put the bytes at `body`.
     */
    BORINK_OUTCOME_KIND_BODY = 1,
    /**
     * No body follows and the read is complete.
     */
    BORINK_OUTCOME_KIND_COMPLETE = 2,
    /**
     * The `If-None-Match` condition held, so Azure sent no body.
     */
    BORINK_OUTCOME_KIND_NOT_MODIFIED = 3,
    /**
     * The condition did not hold, so Azure changed nothing.
     */
    BORINK_OUTCOME_KIND_PRECONDITION_FAILED = 4,
    /**
     * The object or its container does not exist. Read `failure.kind`.
     */
    BORINK_OUTCOME_KIND_NOT_FOUND = 5,
    /**
     * Azure cannot serve the requested range. Read `body.object_size`.
     */
    BORINK_OUTCOME_KIND_RANGE_NOT_SATISFIABLE = 6,
    /**
     * Azure stored the object.
     */
    BORINK_OUTCOME_KIND_DONE = 7,
    /**
     * Azure accepted the removal.
     */
    BORINK_OUTCOME_KIND_ACCEPTED = 8,
    /**
     * The head reports a failure but names no error.
     *
     * Read the response body, cap what you read, and pass it with `failure`
     * to `borink_finish_get_error_body` or one of its two siblings.
     */
    BORINK_OUTCOME_KIND_NEED_ERROR_BODY = 9,
    /**
     * Azure refused the request, or it failed to carry it out.
     */
    BORINK_OUTCOME_KIND_SERVICE_FAILURE = 10,
    /**
     * The call was refused, or the response cannot be read. Read `error`.
     *
     * `error.detail` names the part that was wrong, not the value. You still
     * hold the headers and the shape, so read those for the value itself.
     */
    BORINK_OUTCOME_KIND_INVALID = 11,
    /**
     * The core crate returned a variant that this crate does not know.
     */
    BORINK_OUTCOME_KIND_UNSUPPORTED = 12,
    /**
     * The page of a listing follows in the response body.
     *
     * Read the whole body into one buffer and pass it to
     * `borink_fill_listing`. `body.expected_len` is the length of that body,
     * and the other two values of `body` are absent.
     */
    BORINK_OUTCOME_KIND_PAGE = 13,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_outcome_kind borink_outcome_kind;
#else
typedef uint16_t borink_outcome_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What one entry of a listing page names.
 */
enum borink_entry_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * One object.
     */
    BORINK_ENTRY_KIND_OBJECT = 1,
    /**
     * A group of keys that a delimited listing did not report one by one.
     */
    BORINK_ENTRY_KIND_PREFIX = 2,
    /**
     * A directory that the service keeps as its own entry. Only an Azure
     * account with a hierarchical namespace reports one.
     */
    BORINK_ENTRY_KIND_DIRECTORY = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_entry_kind borink_entry_kind;
#else
typedef uint16_t borink_entry_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * An element that a listing writes for a blob, other than the four that
 * every `borink_list_entry` carries.
 *
 * Name the ones you want in a `borink_property_set` and read the page with
 * `borink_fill_listing_with`, which keeps their values as it goes. Most are
 * written under the properties element; the ones marked otherwise stand
 * beside it. Read anything not listed here with `borink_entry_property`.
 *
 * These are the numbers that the core crate's `BlobProperty` uses. A
 * `const` block in `layout.rs` fails the build if the two lists drift.
 */
enum borink_blob_property
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The access tier: `Hot`, `Cool`, `Cold` or `Archive`.
     */
    BORINK_BLOB_PROPERTY_ACCESS_TIER,
    /**
     * Whether the tier was inferred rather than set.
     */
    BORINK_BLOB_PROPERTY_ACCESS_TIER_INFERRED,
    /**
     * When the tier was last changed.
     */
    BORINK_BLOB_PROPERTY_ACCESS_TIER_CHANGE_TIME,
    /**
     * The progress of a rehydration out of the archive tier.
     */
    BORINK_BLOB_PROPERTY_ARCHIVE_STATUS,
    /**
     * The access control list, on a hierarchical account listing with permissions.
     */
    BORINK_BLOB_PROPERTY_ACL,
    /**
     * `BlockBlob`, `PageBlob` or `AppendBlob`.
     */
    BORINK_BLOB_PROPERTY_BLOB_TYPE,
    /**
     * When the blob was created, in the form of the `Last-Modified` header.
     */
    BORINK_BLOB_PROPERTY_CREATION_TIME,
    /**
     * The media type, as stored with the blob.
     */
    BORINK_BLOB_PROPERTY_CONTENT_TYPE,
    /**
     * The content encoding, as stored with the blob.
     */
    BORINK_BLOB_PROPERTY_CONTENT_ENCODING,
    /**
     * The content language, as stored with the blob.
     */
    BORINK_BLOB_PROPERTY_CONTENT_LANGUAGE,
    /**
     * The CRC64 of the content, if the service holds one.
     */
    BORINK_BLOB_PROPERTY_CONTENT_CRC64,
    /**
     * The MD5 of the content, base64, if the service holds one.
     */
    BORINK_BLOB_PROPERTY_CONTENT_MD5,
    /**
     * The cache control directives, as stored with the blob.
     */
    BORINK_BLOB_PROPERTY_CACHE_CONTROL,
    /**
     * The content disposition, as stored with the blob.
     */
    BORINK_BLOB_PROPERTY_CONTENT_DISPOSITION,
    /**
     * The identifier of the last copy operation onto this blob.
     */
    BORINK_BLOB_PROPERTY_COPY_ID,
    /**
     * The state of that copy: `pending`, `success`, `aborted` or `failed`.
     */
    BORINK_BLOB_PROPERTY_COPY_STATUS,
    /**
     * The URL that copy read from.
     */
    BORINK_BLOB_PROPERTY_COPY_SOURCE,
    /**
     * The bytes copied so far and the total, as `copied/total`.
     */
    BORINK_BLOB_PROPERTY_COPY_PROGRESS,
    /**
     * When that copy finished.
     */
    BORINK_BLOB_PROPERTY_COPY_COMPLETION_TIME,
    /**
     * Why that copy failed or was aborted.
     */
    BORINK_BLOB_PROPERTY_COPY_STATUS_DESCRIPTION,
    /**
     * When a soft-deleted blob was deleted.
     */
    BORINK_BLOB_PROPERTY_DELETED_TIME,
    /**
     * Whether the entry is a soft-deleted blob. Written beside the properties element.
     */
    BORINK_BLOB_PROPERTY_DELETED,
    /**
     * The encryption scope the blob is stored under.
     */
    BORINK_BLOB_PROPERTY_ENCRYPTION_SCOPE,
    /**
     * When the blob expires, on a hierarchical account.
     */
    BORINK_BLOB_PROPERTY_EXPIRY_TIME,
    /**
     * The owning group, on a hierarchical account listing with permissions.
     */
    BORINK_BLOB_PROPERTY_GROUP,
    /**
     * Whether this version is the current one. Written beside the properties element.
     */
    BORINK_BLOB_PROPERTY_IS_CURRENT_VERSION,
    /**
     * Whether the blob is an incremental copy of a page blob snapshot.
     */
    BORINK_BLOB_PROPERTY_INCREMENTAL_COPY,
    /**
     * Until when the immutability policy holds.
     */
    BORINK_BLOB_PROPERTY_IMMUTABILITY_POLICY_UNTIL_DATE,
    /**
     * The immutability policy: `unlocked` or `locked`.
     */
    BORINK_BLOB_PROPERTY_IMMUTABILITY_POLICY_MODE,
    /**
     * Whether the blob is leased: `locked` or `unlocked`.
     */
    BORINK_BLOB_PROPERTY_LEASE_STATUS,
    /**
     * The state of the lease: `available`, `leased`, `expired`, `breaking` or `broken`.
     */
    BORINK_BLOB_PROPERTY_LEASE_STATE,
    /**
     * Whether the lease is `infinite` or `fixed`.
     */
    BORINK_BLOB_PROPERTY_LEASE_DURATION,
    /**
     * Whether a legal hold is set.
     */
    BORINK_BLOB_PROPERTY_LEGAL_HOLD,
    /**
     * The owner, on a hierarchical account listing with permissions.
     */
    BORINK_BLOB_PROPERTY_OWNER,
    /**
     * The POSIX permissions, on a hierarchical account listing with permissions.
     */
    BORINK_BLOB_PROPERTY_PERMISSIONS,
    /**
     * How many days a soft-deleted blob is kept.
     */
    BORINK_BLOB_PROPERTY_REMAINING_RETENTION_DAYS,
    /**
     * The priority of a rehydration out of the archive tier.
     */
    BORINK_BLOB_PROPERTY_REHYDRATE_PRIORITY,
    /**
     * Whether the blob is encrypted at rest.
     */
    BORINK_BLOB_PROPERTY_SERVER_ENCRYPTED,
    /**
     * The snapshot's timestamp, on an entry that names a snapshot. Written beside the properties element.
     */
    BORINK_BLOB_PROPERTY_SNAPSHOT,
    /**
     * How many tags the blob has.
     */
    BORINK_BLOB_PROPERTY_TAG_COUNT,
    /**
     * The version's identifier, on an account that keeps versions. Written beside the properties element.
     */
    BORINK_BLOB_PROPERTY_VERSION_ID,
    /**
     * The sequence number of a page blob.
     */
    BORINK_BLOB_PROPERTY_BLOB_SEQUENCE_NUMBER,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_blob_property borink_blob_property;
#else
typedef uint16_t borink_blob_property;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * A failure, as the two numbers that describe every error of the core crate.
 *
 * `code` is a `borink_error_code`, and `detail` is the discriminant of the
 * value inside it. A `code` of 0 means that nothing failed. Both numbers are
 * append-only: a value defined today keeps its meaning.
 */
typedef struct borink_status {
    /**
     * The kind of failure, or 0 if there is none.
     */
    uint16_t code;
    /**
     * The discriminant of the value inside, or 0 if there is none.
     */
    uint16_t detail;
} borink_status;

/**
 * Bytes that your program owns and lends to a call.
 *
 * A `len` of 0 is an empty value, and `ptr` may then be null.
 *
 * # Lifetime
 *
 * The bytes must stay valid for the whole call. A value returned by a reading
 * call points into the storage that the call read, and is valid until you
 * release or reuse that storage.
 */
typedef struct borink_bytes {
    /**
     * The first byte.
     */
    const uint8_t *ptr;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_bytes;

/**
 * One container, and the token that opens it.
 *
 * Fill one in per client and keep it. Your program owns the three values, and
 * refreshing the token is assigning `token` again.
 *
 * # Lifetime
 *
 * The three values must stay valid for every call that takes this session.
 */
typedef struct borink_session {
    /**
     * The HTTP or HTTPS origin of the storage account.
     */
    struct borink_bytes endpoint;
    /**
     * The container name.
     */
    struct borink_bytes container;
    /**
     * The Entra ID bearer token, without the `Bearer ` prefix.
     */
    struct borink_bytes token;
} borink_session;

/**
 * A range of bytes, as an offset from the start of your request buffer.
 */
typedef struct borink_span {
    /**
     * The offset of the first byte.
     */
    size_t start;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_span;

/**
 * One request header, as two ranges of the request buffer.
 */
typedef struct borink_request_header {
    /**
     * The range that holds the header name.
     */
    struct borink_span name;
    /**
     * The range that holds the header value.
     */
    struct borink_span value;
} borink_request_header;

/**
 * A request head, as ranges of the buffer that holds it.
 */
typedef struct borink_request_head {
    /**
     * Whether the head was written, and what stopped it.
     *
     * A `code` of 0 means that the head is in your buffer.
     */
    struct borink_status status;
    /**
     * The number of bytes that this request head needs.
     *
     * This is the exact size whenever the plan is valid, whether or not the
     * head was written. Size one buffer by it and reuse that buffer.
     */
    size_t required;
    /**
     * The HTTP method, as a `borink_method`.
     */
    uint16_t method;
    /**
     * The range that holds the complete object URL.
     */
    struct borink_span url;
    /**
     * How many of `headers` this request uses.
     */
    size_t header_count;
    /**
     * The headers, in the order that the core crate wrote them.
     */
    struct borink_request_header headers[BORINK_MAX_HEADERS];
} borink_request_head;

/**
 * The byte range that a read requests.
 */
typedef struct borink_range {
    /**
     * Which form of range this is, as a `borink_range_form`.
     */
    uint16_t form;
    /**
     * The first byte, or the length of a suffix.
     */
    uint64_t start;
    /**
     * The byte after the last byte, for a bounded range.
     */
    uint64_t end;
} borink_range;

/**
 * The part of a read plan that holds no borrows.
 *
 * Store one of these while the request is in flight, and pass it to
 * `borink_accept_get_head` when the response arrives. It is the whole
 * per-request context: this crate keeps none of its own.
 */
typedef struct borink_get_shape {
    /**
     * Whether the read asks for bytes or for metadata, as a
     * `borink_get_kind`.
     */
    uint16_t kind;
    /**
     * The byte range that the read requests.
     */
    struct borink_range range;
    /**
     * The precondition that the read carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_get_shape;

/**
 * Storage that a call writes into.
 *
 * A `len` of 0 is an empty buffer, and `ptr` may then be null.
 */
typedef struct borink_bytes_mut {
    /**
     * The first byte.
     */
    uint8_t *ptr;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_bytes_mut;

/**
 * The part of a write plan that holds no borrows.
 */
typedef struct borink_put_shape {
    /**
     * The precondition that the write carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_put_shape;

/**
 * The part of a removal plan that holds no borrows.
 */
typedef struct borink_delete_shape {
    /**
     * What the removal takes with it, as a `borink_delete_kind`.
     */
    uint16_t kind;
    /**
     * The precondition that the removal carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_delete_shape;

/**
 * A number that a response head may not carry.
 */
typedef struct borink_maybe_u64 {
    /**
     * Whether the head carried this number.
     */
    bool present;
    /**
     * The number.
     */
    uint64_t value;
} borink_maybe_u64;

/**
 * Bytes that a response head may not carry.
 *
 * `present` and an empty `bytes` are different facts. A header that the
 * service sent empty is present, and one it did not send is not.
 *
 * # Lifetime
 *
 * `bytes` points into the storage that the `borink_header_ref`s of the call
 * pointed into, or into the error body that you passed. It is valid until you
 * release or reuse that storage.
 */
typedef struct borink_maybe_bytes {
    /**
     * Whether the head carried this value.
     */
    bool present;
    /**
     * The bytes of it.
     */
    struct borink_bytes bytes;
} borink_maybe_bytes;

/**
 * Object metadata, borrowed from the response head.
 *
 * # Lifetime
 *
 * Every field points into the storage that the `borink_header_ref`s pointed
 * into, and is valid until you release or reuse it.
 */
typedef struct borink_object_meta {
    /**
     * The size of the whole object.
     */
    struct borink_maybe_u64 size;
    /**
     * The entity tag.
     */
    struct borink_maybe_bytes e_tag;
    /**
     * The value of the `Last-Modified` header.
     */
    struct borink_maybe_bytes last_modified;
    /**
     * The version identifier.
     */
    struct borink_maybe_bytes version;
    /**
     * The value of the `Content-Encoding` header.
     */
    struct borink_maybe_bytes content_encoding;
} borink_object_meta;

/**
 * Where the bytes of the response body belong in the object.
 */
typedef struct borink_body_window {
    /**
     * The offset in the object of the first byte of the response body.
     */
    uint64_t object_offset;
    /**
     * The exact length of the response body.
     */
    struct borink_maybe_u64 expected_len;
    /**
     * The size of the whole object.
     */
    struct borink_maybe_u64 object_size;
} borink_body_window;

/**
 * A response head that reports a failure.
 *
 * Store one of these and pass it back to `borink_finish_get_error_body` to
 * finish a `NeedErrorBody`.
 *
 * A `NotFound` fills `kind` alone. A missing object is not a failure of the
 * head: it names an error and carries no status and no category, so both are
 * 0.
 *
 * # Lifetime
 *
 * `request_id` points into the storage that the `borink_header_ref`s pointed
 * into. Copy it if you keep this value past that storage.
 */
typedef struct borink_failure {
    /**
     * The HTTP status code.
     */
    uint16_t status;
    /**
     * The category of the failure, as a `borink_failure_class`. Use it to
     * decide whether to retry.
     *
     * This is `class` in the core crate, which C++ cannot spell.
     */
    uint16_t class_;
    /**
     * The specific error that the head or the body named, as a
     * `borink_service_error`.
     */
    uint16_t kind;
    /**
     * The value of the `x-ms-request-id` header.
     */
    struct borink_maybe_bytes request_id;
} borink_failure;

/**
 * The result of reading one response head.
 *
 * One value describes a read, a write and a removal. The fields that the
 * operation does not fill are absent.
 *
 * # Lifetime
 *
 * Everything that this value borrows is valid until you release or reuse the
 * storage that the `borink_header_ref`s pointed into.
 */
typedef struct borink_outcome {
    /**
     * Which outcome this is, as a `borink_outcome_kind`.
     */
    uint16_t kind;
    /**
     * The metadata from the head.
     */
    struct borink_object_meta meta;
    /**
     * Where the bytes of the body belong.
     */
    struct borink_body_window body;
    /**
     * The failure, for `NeedErrorBody`, `ServiceFailure` and `NotFound`.
     */
    struct borink_failure failure;
    /**
     * Why the call was refused, for `Invalid`.
     */
    struct borink_status error;
} borink_outcome;

/**
 * One response header, as the bytes that you already hold.
 *
 * Build a small array of these from wherever your HTTP library keeps the
 * head, and reuse the array. This crate copies none of it.
 *
 * # Lifetime
 *
 * Both values must stay valid for as long as you use the outcome that the
 * reading call returns.
 */
typedef struct borink_header_ref {
    /**
     * The header name. A name that is not text is ignored.
     */
    struct borink_bytes name;
    /**
     * The header value.
     */
    struct borink_bytes value;
} borink_header_ref;

/**
 * A number that a plan may not carry.
 */
typedef struct borink_maybe_u32 {
    /**
     * Whether the plan carries this number.
     */
    bool present;
    /**
     * The number.
     */
    uint32_t value;
} borink_maybe_u32;

/**
 * The part of a listing plan that holds no borrows.
 */
typedef struct borink_list_shape {
    /**
     * Whether the listing groups the keys at each `/` after the prefix.
     *
     * A delimited listing reports each group once, as an entry of kind
     * `Prefix`, instead of reporting every key in it.
     */
    bool delimited;
    /**
     * The most entries that one page reports.
     *
     * An absent number asks for the service's maximum, which Azure also
     * applies to any larger number: it answers 5,000 entries and a marker
     * rather than refusing. The service may also report fewer entries than
     * you asked for and still name a next page.
     */
    struct borink_maybe_u32 max_results;
} borink_list_shape;

/**
 * What one call to `borink_fill_listing` read.
 *
 * # Lifetime
 *
 * `next_marker` points into the body that the call read, and is valid until
 * you release or reuse that buffer.
 */
typedef struct borink_fill {
    /**
     * Whether the page could be read.
     *
     * A `code` of 0 means that the entries are in your array. When it is
     * `Capacity`, `required` is set; every other field is absent when the
     * code is not 0.
     */
    struct borink_status status;
    /**
     * The number of entries written into your array.
     *
     * The entries after these are untouched.
     */
    size_t filled;
    /**
     * The number of entries that the page holds, when the array had no room
     * for all of them.
     *
     * The body has been decoded by then and cannot be read again. Ask the
     * service for the page again, with an array of this many entries, or ask
     * for a page no larger than your array.
     */
    size_t required;
    /**
     * The text that names the next page.
     *
     * Absent when the listing is complete. Copy the bytes into your own
     * storage and pass them as the marker of the next request.
     */
    struct borink_maybe_bytes next_marker;
} borink_fill;

/**
 * One entry of a listing page.
 *
 * # Lifetime
 *
 * `key`, `e_tag` and `last_modified` point into the body that
 * `borink_fill_listing` read. They are valid until you release or reuse that
 * buffer, or until the next call that reads it.
 */
typedef struct borink_list_entry {
    /**
     * What this entry names, as a `borink_entry_kind`.
     */
    uint16_t kind;
    /**
     * The object key, the shared start of the group, or the directory path.
     *
     * The bytes are UTF-8 text.
     */
    struct borink_bytes key;
    /**
     * The size of the object. Absent for a group and for a directory.
     */
    struct borink_maybe_u64 size;
    /**
     * The entity tag, as the listing wrote it.
     *
     * Azure lists an entity tag without the quotes that the `ETag` header
     * carries. Both forms condition a request.
     */
    struct borink_maybe_bytes e_tag;
    /**
     * The value that the listing gave for the last modification, in the form
     * that the `Last-Modified` header uses.
     */
    struct borink_maybe_bytes last_modified;
    /**
     * This entry as the service wrote it, from its opening tag to its closing
     * one.
     *
     * Read a value that the fields above do not carry out of these bytes,
     * with `borink_entry_property` or `borink_entry_properties`.
     */
    struct borink_bytes raw;
} borink_list_entry;

/**
 * The properties that one `borink_fill_listing_with` call is asked for.
 *
 * One bit per property, at the bit that the property's number names. Start
 * from a zeroed value and add each property with `borink_property_set_with`.
 */
typedef struct borink_property_set {
    /**
     * The bits. Bit `n` stands for the property numbered `n`.
     */
    uint64_t mask;
} borink_property_set;

/**
 * A walk over the values that one entry holds.
 *
 * `borink_entry_properties` starts one and `borink_next_property` steps it.
 * The two values are this crate's own: keep the walk and pass it back.
 *
 * # Lifetime
 *
 * The walk points into the body that `borink_fill_listing` read, and is valid
 * for as long as the entry it came from.
 */
typedef struct borink_properties {
    /**
     * The bytes of the entry that the walk has not read.
     */
    struct borink_bytes remaining;
    /**
     * Whether the walk stands inside the properties element.
     */
    bool within;
} borink_properties;

/**
 * One value that an entry holds.
 *
 * # Lifetime
 *
 * Both values point into the body that `borink_fill_listing` read, and are
 * valid until you release or reuse that buffer.
 */
typedef struct borink_property {
    /**
     * Whether the walk read one. A walk that has ended reports `false`.
     */
    bool present;
    /**
     * The name of the element that held the value.
     */
    struct borink_bytes name;
    /**
     * The value, as the service wrote it.
     */
    struct borink_bytes value;
} borink_property;

/**
 * What a C compiler computes for the structs that cross this boundary.
 *
 * Fill every field with the `sizeof`, `alignof` or `offsetof` that its name
 * gives, and pass it to `borink_layout_disagrees`.
 */
typedef struct borink_layout {
    size_t sizeof_bytes;
    size_t alignof_bytes;
    size_t offsetof_bytes_len;
    size_t sizeof_bytes_mut;
    size_t alignof_bytes_mut;
    size_t sizeof_span;
    size_t offsetof_span_len;
    size_t sizeof_maybe_bytes;
    size_t alignof_maybe_bytes;
    size_t offsetof_maybe_bytes_bytes;
    size_t sizeof_maybe_u64;
    size_t alignof_maybe_u64;
    size_t offsetof_maybe_u64_value;
    size_t sizeof_status;
    size_t offsetof_status_detail;
    size_t sizeof_session;
    size_t offsetof_session_container;
    size_t offsetof_session_token;
    size_t sizeof_range;
    size_t alignof_range;
    size_t offsetof_range_start;
    size_t offsetof_range_end;
    size_t sizeof_get_shape;
    size_t offsetof_get_shape_range;
    size_t offsetof_get_shape_condition;
    size_t sizeof_put_shape;
    size_t sizeof_delete_shape;
    size_t offsetof_delete_shape_condition;
    size_t sizeof_request_header;
    size_t offsetof_request_header_value;
    size_t sizeof_request_head;
    size_t alignof_request_head;
    size_t offsetof_request_head_required;
    size_t offsetof_request_head_method;
    size_t offsetof_request_head_url;
    size_t offsetof_request_head_header_count;
    size_t offsetof_request_head_headers;
    size_t sizeof_header_ref;
    size_t offsetof_header_ref_value;
    size_t sizeof_object_meta;
    size_t offsetof_object_meta_e_tag;
    size_t offsetof_object_meta_last_modified;
    size_t offsetof_object_meta_version;
    size_t offsetof_object_meta_content_encoding;
    size_t sizeof_body_window;
    size_t offsetof_body_window_expected_len;
    size_t offsetof_body_window_object_size;
    size_t sizeof_failure;
    size_t offsetof_failure_class;
    size_t offsetof_failure_kind;
    size_t offsetof_failure_request_id;
    size_t sizeof_outcome;
    size_t alignof_outcome;
    size_t offsetof_outcome_meta;
    size_t offsetof_outcome_body;
    size_t offsetof_outcome_failure;
    size_t offsetof_outcome_error;
    size_t sizeof_maybe_u32;
    size_t alignof_maybe_u32;
    size_t offsetof_maybe_u32_value;
    size_t sizeof_list_shape;
    size_t offsetof_list_shape_max_results;
    size_t sizeof_list_entry;
    size_t alignof_list_entry;
    size_t offsetof_list_entry_key;
    size_t offsetof_list_entry_size;
    size_t offsetof_list_entry_e_tag;
    size_t offsetof_list_entry_last_modified;
    size_t offsetof_list_entry_raw;
    size_t sizeof_properties;
    size_t alignof_properties;
    size_t offsetof_properties_within;
    size_t sizeof_property;
    size_t alignof_property;
    size_t offsetof_property_name;
    size_t offsetof_property_value;
    size_t sizeof_fill;
    size_t alignof_fill;
    size_t offsetof_fill_filled;
    size_t offsetof_fill_required;
    size_t offsetof_fill_next_marker;
    size_t sizeof_property_set;
    size_t alignof_property_set;
} borink_layout;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Reports what is wrong with `session`, if anything.
 *
 * A `code` of 0 means that the session can build requests. Every other call
 * makes the same check, so this exists to fail early.
 *
 * # Safety
 *
 * `session` must be null or point at one readable `borink_session` whose
 * three values are each readable for their length.
 */
struct borink_status borink_validate(const struct borink_session *session);

/**
 * Writes the request head of a read into `buf`.
 *
 * Pass an empty `condition_value` if `shape` carries no condition. Pass an
 * empty `buf` to learn the size that this request needs.
 *
 * # Safety
 *
 * `session` and `shape` must each be null or point at one readable value.
 * `key`, `condition_value` and `buf` must each address their stated length,
 * and `buf` must be reached through nothing else during the call.
 */
struct borink_request_head borink_encode_get(const struct borink_session *session,
                                             const struct borink_get_shape *shape,
                                             struct borink_bytes key,
                                             struct borink_bytes condition_value,
                                             struct borink_bytes_mut buf,
                                             uint64_t unix_seconds);

/**
 * Writes the request head of a write into `buf`.
 *
 * The head states `content_len`. You send those bytes yourself.
 *
 * # Safety
 *
 * As `borink_encode_get`.
 */
struct borink_request_head borink_encode_put(const struct borink_session *session,
                                             const struct borink_put_shape *shape,
                                             struct borink_bytes key,
                                             struct borink_bytes condition_value,
                                             struct borink_bytes_mut buf,
                                             uint64_t content_len,
                                             uint64_t unix_seconds);

/**
 * Writes the request head of a removal into `buf`.
 *
 * # Safety
 *
 * As `borink_encode_get`.
 */
struct borink_request_head borink_encode_delete(const struct borink_session *session,
                                                const struct borink_delete_shape *shape,
                                                struct borink_bytes key,
                                                struct borink_bytes condition_value,
                                                struct borink_bytes_mut buf,
                                                uint64_t unix_seconds);

/**
 * Reads the response head of a read.
 *
 * Pass the same `shape` that you passed to `borink_encode_get`, and one
 * `borink_header_ref` per response header. The outcome points into the same
 * bytes as those headers.
 *
 * # Safety
 *
 * `session` and `shape` must each be null or point at one readable value.
 * `headers` must address `header_count` readable values.
 *
 * # Lifetime
 *
 * The bytes that `headers` points at must stay valid, and must not move, for
 * as long as you use the returned outcome.
 */
struct borink_outcome borink_accept_get_head(const struct borink_session *session,
                                             const struct borink_get_shape *shape,
                                             uint16_t status,
                                             const struct borink_header_ref *headers,
                                             size_t header_count);

/**
 * Reads the response head of a write.
 *
 * # Safety
 *
 * As `borink_accept_get_head`.
 *
 * # Lifetime
 *
 * As `borink_accept_get_head`.
 */
struct borink_outcome borink_accept_put_head(const struct borink_session *session,
                                             const struct borink_put_shape *shape,
                                             uint16_t status,
                                             const struct borink_header_ref *headers,
                                             size_t header_count);

/**
 * Reads the response head of a removal.
 *
 * # Safety
 *
 * As `borink_accept_get_head`.
 *
 * # Lifetime
 *
 * As `borink_accept_get_head`.
 */
struct borink_outcome borink_accept_delete_head(const struct borink_session *session,
                                                const struct borink_delete_shape *shape,
                                                uint16_t status,
                                                const struct borink_header_ref *headers,
                                                size_t header_count);

/**
 * Finishes a read whose head asked for the error body.
 *
 * Pass the `failure` of that outcome and the body that you read. Pass an
 * empty body if you read none: the outcome is then final with the error
 * unnamed.
 *
 * # Safety
 *
 * `session` and `failure` must each be null or point at one readable value.
 * `body` must address its stated length.
 *
 * # Lifetime
 *
 * `failure->request_id` must still point at valid bytes, and they must stay
 * valid for as long as you use the returned outcome. So must `body`.
 */
struct borink_outcome borink_finish_get_error_body(const struct borink_session *session,
                                                   const struct borink_failure *failure,
                                                   struct borink_bytes body);

/**
 * Finishes a write whose head asked for the error body.
 *
 * # Safety
 *
 * As `borink_finish_get_error_body`.
 *
 * # Lifetime
 *
 * As `borink_finish_get_error_body`.
 */
struct borink_outcome borink_finish_put_error_body(const struct borink_session *session,
                                                   const struct borink_failure *failure,
                                                   struct borink_bytes body);

/**
 * Finishes a removal whose head asked for the error body.
 *
 * # Safety
 *
 * As `borink_finish_get_error_body`.
 *
 * # Lifetime
 *
 * As `borink_finish_get_error_body`.
 */
struct borink_outcome borink_finish_delete_error_body(const struct borink_session *session,
                                                      const struct borink_failure *failure,
                                                      struct borink_bytes body);

/**
 * Writes the request head of one page of a listing into `buf`.
 *
 * An empty `prefix` lists the whole container. Pass an empty `marker` for the
 * first page, and the `next_marker` of the last fill for every page after it.
 *
 * # Safety
 *
 * `session` and `shape` must each be null or point at one readable value.
 * `prefix`, `marker` and `buf` must each address their stated length, and
 * `buf` must be reached through nothing else during the call.
 */
struct borink_request_head borink_encode_list(const struct borink_session *session,
                                              const struct borink_list_shape *shape,
                                              struct borink_bytes prefix,
                                              struct borink_bytes marker,
                                              struct borink_bytes_mut buf,
                                              uint64_t unix_seconds);

/**
 * Reads the response head of a listing.
 *
 * This call takes no shape: it checks nothing in the response against the
 * plan.
 *
 * # Safety
 *
 * `session` must be null or point at one readable value. `headers` must
 * address `header_count` readable values.
 *
 * # Lifetime
 *
 * The bytes that `headers` points at must stay valid, and must not move, for
 * as long as you use the returned outcome.
 */
struct borink_outcome borink_accept_list_head(const struct borink_session *session,
                                              uint16_t status,
                                              const struct borink_header_ref *headers,
                                              size_t header_count);

/**
 * Finishes a listing whose head asked for the error body.
 *
 * # Safety
 *
 * As `borink_finish_get_error_body`.
 *
 * # Lifetime
 *
 * As `borink_finish_get_error_body`.
 */
struct borink_outcome borink_finish_list_error_body(const struct borink_session *session,
                                                    const struct borink_failure *failure,
                                                    struct borink_bytes body);

/**
 * Reads a page out of the response body of a listing.
 *
 * Pass the whole body that the `Page` outcome announced, and an array of
 * `capacity` entries to write it into. Reading is destructive. This call
 * decodes the text of the body where it stands, so a body that has been read
 * is no longer a document.
 *
 * Your array must hold the whole page. An array of `max_results` entries
 * always does. A smaller one is refused with `Capacity`, and `required` says
 * how many entries the page holds; the body cannot be read again by then.
 *
 * # Safety
 *
 * `session` must be null or point at one readable value. `body` must address
 * its stated length and be reached through nothing else during the call.
 * `into` must address `capacity` writable entries.
 *
 * # Lifetime
 *
 * Every entry, and `next_marker`, point into `body`. They are valid until you
 * release or reuse that buffer.
 */
struct borink_fill borink_fill_listing(const struct borink_session *session,
                                       struct borink_bytes_mut body,
                                       struct borink_list_entry *into,
                                       size_t capacity);

/**
 * Reads a page the way `borink_fill_listing` does, and keeps the values of
 * the properties in `wanted` as it goes.
 *
 * `values` is your array of rows: one row per entry of `into`, each
 * `borink_property_set_len(wanted)` values long, so `capacity` rows in all.
 * The value that entry `i` gave for a property `p` is
 * `values[i * len + borink_property_slot(wanted, p)]`. It is absent where
 * the entry wrote no such element, and present and empty where it wrote the
 * element empty. A group of keys has every value absent. If `values` holds
 * fewer rows than `capacity`, that many rows is the capacity.
 *
 * Reading the page costs the same as `borink_fill_listing`, whatever the
 * set holds.
 *
 * # Safety
 *
 * As `borink_fill_listing`, and `values` must address `value_capacity`
 * writable values.
 *
 * # Lifetime
 *
 * Every value points into `body`, like the entries.
 */
struct borink_fill borink_fill_listing_with(const struct borink_session *session,
                                            struct borink_bytes_mut body,
                                            struct borink_list_entry *into,
                                            size_t capacity,
                                            struct borink_property_set wanted,
                                            struct borink_maybe_bytes *values,
                                            size_t value_capacity);

/**
 * Adds a property to a set.
 *
 * `property` is a `borink_blob_property`. A number that names no property
 * leaves the set as it was.
 */
struct borink_property_set borink_property_set_with(struct borink_property_set set,
                                                    uint16_t property);

/**
 * Returns how many properties a set holds, which is how many values each
 * row of `borink_fill_listing_with` has.
 */
size_t borink_property_set_len(struct borink_property_set set);

/**
 * Returns where a property's value stands in a row: its rank among the
 * set's members, in the order of their numbers.
 *
 * For a property the set does not hold, or a number that names none, this
 * is the length of the row, which is one past its last value.
 */
size_t borink_property_slot(struct borink_property_set set, uint16_t property);

/**
 * Returns the element name of a property, as the service writes it. Empty
 * for a number that names no property.
 */
struct borink_bytes borink_property_name(uint16_t property);

/**
 * Returns the value that one entry gave for a property.
 *
 * The name is matched exactly, against the elements of the entry and of its
 * properties element: `AccessTier` and `Creation-Time` on Azure. An absent
 * value means the entry wrote no such property, which is not the same fact as
 * a property it wrote empty.
 *
 * Each call reads the entry again. Read more than one or two with
 * `borink_entry_properties`, which reads it once.
 *
 * The three values that the entry carries are not read back this way. Reading
 * the page decoded them where they stood, so the element that held one now
 * holds the decoded text and what the decoding left behind. Read `key`,
 * `e_tag` and `last_modified` from the entry.
 *
 * # Safety
 *
 * `entry` must be null or point at one readable value whose `raw` addresses
 * its stated length. `name` must address its stated length.
 *
 * # Lifetime
 *
 * The value points into the body that the entry points into.
 */
struct borink_maybe_bytes borink_entry_property(const struct borink_list_entry *entry,
                                                struct borink_bytes name);

/**
 * Starts a walk over the values that one entry holds.
 *
 * Step it with `borink_next_property`, which reports one value per call and
 * reads the entry once over the whole walk. A null `entry` starts a walk that
 * has already ended.
 *
 * # Safety
 *
 * As `borink_entry_property`.
 *
 * # Lifetime
 *
 * The walk points into the body that the entry points into.
 */
struct borink_properties borink_entry_properties(const struct borink_list_entry *entry);

/**
 * Reads the next value of a walk, and steps the walk past it.
 *
 * An element that holds other elements, such as the metadata of an object,
 * reports those bytes as its value. The properties element is stepped into
 * rather than reported. A walk that has ended reports an absent value, and
 * stays ended.
 *
 * # Safety
 *
 * `walk` must be null or point at one writable `borink_properties` whose
 * `remaining` addresses its stated length.
 *
 * # Lifetime
 *
 * The value points into the body that the walk points into.
 */
struct borink_property borink_next_property(struct borink_properties *walk);

/**
 * Writes the text of a listed value with its references resolved.
 *
 * Use this on a value that `borink_entry_property` returned, which holds the
 * bytes that the service wrote. XML writes an `&` as `&amp;`, and a character
 * that the document cannot carry as `&#233;`.
 *
 * Copies `value` into `into` and returns what it wrote, which is never longer
 * than `value`. An absent value means that `into` is shorter than `value`, or
 * that `value` holds a reference that no listing declares.
 *
 * # Safety
 *
 * `value` must address its stated length. `into` must address its stated
 * length and be reached through nothing else during the call.
 *
 * # Lifetime
 *
 * The bytes returned are `into`, so they are valid until you release or
 * reuse it.
 */
struct borink_maybe_bytes borink_decode_into(struct borink_bytes value,
                                             struct borink_bytes_mut into);

/**
 * Writes an entity tag from a listing in the quoted form that HTTP defines.
 *
 * A listing writes an entity tag without the quotes that the `ETag` header
 * carries. Pass `borink_list_entry.e_tag` here to get the form that a
 * condition takes. `into` needs at most two bytes more than `listed`, and a
 * shorter one writes nothing and returns an absent value.
 *
 * # Safety
 *
 * `listed` must address its stated length. `into` must address its stated
 * length and be reached through nothing else during the call.
 *
 * # Lifetime
 *
 * The bytes returned are `into`, so they are valid until you release or
 * reuse it.
 */
struct borink_maybe_bytes borink_quoted_etag(struct borink_bytes listed,
                                             struct borink_bytes_mut into);

/**
 * Reads an HTTP date as milliseconds since the Unix epoch.
 *
 * Pass `borink_list_entry.last_modified`, or the same value of a
 * `borink_object_meta`. A value that is not an RFC 1123 date is absent.
 *
 * # Safety
 *
 * `value` must address its stated length.
 */
struct borink_maybe_u64 borink_http_date_ms(struct borink_bytes value);

/**
 * Writes one sentence naming what `outcome` says.
 *
 * Returns the length of the whole sentence, which may be longer than `into`.
 * The part that fits is written. A null `outcome` writes nothing and returns
 * 0.
 *
 * # Safety
 *
 * `outcome` must be null or point at one readable value whose borrowed fields
 * still address valid bytes. `into` must address its stated length and be
 * reached through nothing else during the call.
 */
size_t borink_describe(const struct borink_outcome *outcome, struct borink_bytes_mut into);

/**
 * Writes one sentence naming what `status` says.
 *
 * Returns the length of the whole sentence, exactly as `borink_describe`.
 *
 * # Safety
 *
 * `into` must address its stated length and be reached through nothing else
 * during the call.
 */
size_t borink_describe_status(struct borink_status status, struct borink_bytes_mut into);

/**
 * Compares the layout a C compiler computed with the one this crate uses.
 *
 * Returns the number of fields of `probe` that differ, and 0 when every one
 * agrees. Call it once at startup, or from a static assertion in your own
 * test, before you read a field of any struct here.
 *
 * # Safety
 *
 * `probe` must be null or point at one readable `borink_layout`. A null
 * `probe` counts every field as different.
 */
size_t borink_layout_disagrees(const struct borink_layout *probe);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BORINK_OBJECT_STORAGE_H */
