// Azure Blob Storage for a program that owns its memory and its I/O.
//
// GENERATED by cbindgen from crates/object-storage-c/src/lib.rs. Do not edit.
// Edit the Rust source and build the crate; CI fails if this file and that
// source disagree.

#ifndef BORINK_OBJECT_STORAGE_H
#define BORINK_OBJECT_STORAGE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * The most headers that one request head carries.
 *
 * This is the core crate's own bound, and the array in `borink_request_head`
 * has exactly this many slots. The assertion below stops the build if the
 * core crate raises it.
 */
#define BORINK_MAX_HEADERS 6

/**
 * Which kind of failure a `borink_status` carries.
 *
 * These are the numbers that the core crate's error code uses.
 */
enum borink_error_code
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Nothing failed.
     */
    BORINK_ERROR_CODE_NONE = 0,
    /**
     * The endpoint is not an ASCII HTTP or HTTPS origin.
     */
    BORINK_ERROR_CODE_INVALID_ENDPOINT = 1,
    /**
     * The container name is not usable in a request.
     */
    BORINK_ERROR_CODE_INVALID_CONTAINER = 2,
    /**
     * The token is not usable as one HTTP header value.
     */
    BORINK_ERROR_CODE_INVALID_TOKEN = 3,
    /**
     * The plan cannot become a request. `detail` says why.
     */
    BORINK_ERROR_CODE_INVALID_PLAN = 4,
    /**
     * The buffer is too small. Grow it to `required` and call again.
     */
    BORINK_ERROR_CODE_CAPACITY = 5,
    /**
     * The response cannot be read. `detail` says which part was wrong.
     */
    BORINK_ERROR_CODE_RESPONSE = 6,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_error_code borink_error_code;
#else
typedef uint16_t borink_error_code;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The HTTP method of a request.
 */
enum borink_method
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * `GET`.
     */
    BORINK_METHOD_GET = 1,
    /**
     * `HEAD`.
     */
    BORINK_METHOD_HEAD = 2,
    /**
     * `PUT`.
     */
    BORINK_METHOD_PUT = 3,
    /**
     * `DELETE`.
     */
    BORINK_METHOD_DELETE = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_method borink_method;
#else
typedef uint16_t borink_method;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a read asks the service to return.
 */
enum borink_get_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The bytes of the object.
     */
    BORINK_GET_KIND_BYTES = 1,
    /**
     * The metadata of the object, without its bytes.
     */
    BORINK_GET_KIND_METADATA = 2,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_get_kind borink_get_kind;
#else
typedef uint16_t borink_get_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Which form of byte range a read requests.
 */
enum borink_range_form
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Every byte of the object. `start` and `end` are 0.
     */
    BORINK_RANGE_FORM_WHOLE = 1,
    /**
     * The half-open interval `start..end`.
     */
    BORINK_RANGE_FORM_BOUNDED = 2,
    /**
     * Every byte from `start` to the end of the object.
     */
    BORINK_RANGE_FORM_OFFSET = 3,
    /**
     * The last `start` bytes. Azure Blob Storage refuses this form.
     */
    BORINK_RANGE_FORM_SUFFIX = 4,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_range_form borink_range_form;
#else
typedef uint16_t borink_range_form;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The ETag precondition that a request carries.
 *
 * A request that carries one passes the entity tag as `condition_value`. A
 * request that carries none passes an empty `condition_value`.
 */
enum borink_condition
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The request carries no precondition.
     */
    BORINK_CONDITION_NONE = 1,
    /**
     * The request succeeds only if the current ETag matches.
     */
    BORINK_CONDITION_IF_MATCH = 2,
    /**
     * The request succeeds only if the current ETag differs.
     */
    BORINK_CONDITION_IF_NONE_MATCH = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_condition borink_condition;
#else
typedef uint16_t borink_condition;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a removal takes with it.
 */
enum borink_delete_kind
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * Remove the object alone. Azure refuses this if it has snapshots.
     */
    BORINK_DELETE_KIND_OBJECT = 1,
    /**
     * Remove the object and its snapshots.
     */
    BORINK_DELETE_KIND_OBJECT_AND_SNAPSHOTS = 2,
    /**
     * Remove the snapshots and keep the object.
     */
    BORINK_DELETE_KIND_SNAPSHOTS_ONLY = 3,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_delete_kind borink_delete_kind;
#else
typedef uint16_t borink_delete_kind;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The category of a service failure.
 *
 * These are the numbers that the core crate's failure class uses. A number
 * that is not listed here comes from a later version of that crate. It
 * crosses unchanged, never as a substitute.
 */
enum borink_failure_class
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The failure carries no category.
     */
    BORINK_FAILURE_CLASS_NONE = 0,
    /**
     * The service rejected the credentials or the authorization.
     */
    BORINK_FAILURE_CLASS_AUTH = 1,
    /**
     * The service throttled the request. You can retry it later.
     */
    BORINK_FAILURE_CLASS_THROTTLED = 2,
    /**
     * The service failed, or it was unavailable.
     */
    BORINK_FAILURE_CLASS_SERVER = 3,
    /**
     * The service answered with a redirect.
     */
    BORINK_FAILURE_CLASS_REDIRECT = 4,
    /**
     * Any other failure, such as a malformed request.
     */
    BORINK_FAILURE_CLASS_OTHER = 5,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_failure_class borink_failure_class;
#else
typedef uint16_t borink_failure_class;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * The specific error that the service named.
 *
 * These are the numbers that the core crate's service error kind uses, and
 * they cross unchanged in both directions.
 */
enum borink_service_error
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * The service named no error.
     */
    BORINK_SERVICE_ERROR_NONE = 0,
    /**
     * The object does not exist.
     */
    BORINK_SERVICE_ERROR_NOT_FOUND = 1,
    /**
     * The container does not exist.
     */
    BORINK_SERVICE_ERROR_NO_SUCH_CONTAINER = 2,
    /**
     * The object or the container already exists.
     */
    BORINK_SERVICE_ERROR_ALREADY_EXISTS = 3,
    /**
     * The service rejected the credentials or the authorization.
     */
    BORINK_SERVICE_ERROR_UNAUTHORIZED = 4,
    /**
     * A precondition on the request did not hold.
     */
    BORINK_SERVICE_ERROR_PRECONDITION = 5,
    /**
     * The service cannot serve the requested byte range.
     */
    BORINK_SERVICE_ERROR_RANGE_NOT_SATISFIABLE = 6,
    /**
     * The service throttled the request.
     */
    BORINK_SERVICE_ERROR_THROTTLED = 7,
    /**
     * The service timed out while it processed the request.
     */
    BORINK_SERVICE_ERROR_TIMEOUT = 8,
    /**
     * The service failed, or it was unavailable.
     */
    BORINK_SERVICE_ERROR_SERVICE = 9,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_service_error borink_service_error;
#else
typedef uint16_t borink_service_error;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a response tells you to do.
 */
enum borink_disposition
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : uint16_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
    /**
     * A body follows. Read it and put the bytes at `body`.
     */
    BORINK_DISPOSITION_BODY = 1,
    /**
     * No body follows and the read is complete.
     */
    BORINK_DISPOSITION_COMPLETE = 2,
    /**
     * The `If-None-Match` condition held, so Azure sent no body.
     */
    BORINK_DISPOSITION_NOT_MODIFIED = 3,
    /**
     * The condition did not hold, so Azure changed nothing.
     */
    BORINK_DISPOSITION_PRECONDITION_FAILED = 4,
    /**
     * The object or its container does not exist. Read `failure.kind`.
     */
    BORINK_DISPOSITION_NOT_FOUND = 5,
    /**
     * Azure cannot serve the requested range. Read `body.object_size`.
     */
    BORINK_DISPOSITION_RANGE_NOT_SATISFIABLE = 6,
    /**
     * Azure stored the object.
     */
    BORINK_DISPOSITION_DONE = 7,
    /**
     * Azure accepted the removal.
     */
    BORINK_DISPOSITION_ACCEPTED = 8,
    /**
     * The head reports a failure but names no error.
     *
     * Read the response body, cap what you read, and pass it with `failure`
     * to `borink_finish_get_error_body` or one of its two siblings.
     */
    BORINK_DISPOSITION_NEED_ERROR_BODY = 9,
    /**
     * Azure refused the request, or it failed to carry it out.
     */
    BORINK_DISPOSITION_SERVICE_FAILURE = 10,
    /**
     * The call was refused, or the response cannot be read. Read `error`.
     *
     * `error.detail` names the part that was wrong, not the value. You still
     * hold the headers and the shape, so read those for the value itself.
     */
    BORINK_DISPOSITION_INVALID = 11,
    /**
     * The core crate returned a variant that this crate does not know.
     */
    BORINK_DISPOSITION_UNSUPPORTED = 12,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum borink_disposition borink_disposition;
#else
typedef uint16_t borink_disposition;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * What a C compiler computes for the structs that cross this boundary.
 *
 * Fill every field with the `sizeof`, `alignof` or `offsetof` that its name
 * gives, and pass it to `borink_layout_disagrees`.
 */
typedef struct borink_layout {
    size_t sizeof_bytes;
    size_t alignof_bytes;
    size_t offsetof_bytes_len;
    size_t sizeof_bytes_mut;
    size_t alignof_bytes_mut;
    size_t sizeof_span;
    size_t offsetof_span_len;
    size_t sizeof_maybe_bytes;
    size_t alignof_maybe_bytes;
    size_t offsetof_maybe_bytes_bytes;
    size_t sizeof_maybe_u64;
    size_t alignof_maybe_u64;
    size_t offsetof_maybe_u64_value;
    size_t sizeof_status;
    size_t offsetof_status_detail;
    size_t sizeof_session;
    size_t offsetof_session_container;
    size_t offsetof_session_token;
    size_t sizeof_range;
    size_t alignof_range;
    size_t offsetof_range_start;
    size_t offsetof_range_end;
    size_t sizeof_get_shape;
    size_t offsetof_get_shape_range;
    size_t offsetof_get_shape_condition;
    size_t sizeof_put_shape;
    size_t sizeof_delete_shape;
    size_t offsetof_delete_shape_condition;
    size_t sizeof_request_header;
    size_t offsetof_request_header_value;
    size_t sizeof_request_head;
    size_t alignof_request_head;
    size_t offsetof_request_head_required;
    size_t offsetof_request_head_method;
    size_t offsetof_request_head_url;
    size_t offsetof_request_head_header_count;
    size_t offsetof_request_head_headers;
    size_t sizeof_header_ref;
    size_t offsetof_header_ref_value;
    size_t sizeof_object_meta;
    size_t offsetof_object_meta_e_tag;
    size_t offsetof_object_meta_last_modified;
    size_t offsetof_object_meta_version;
    size_t offsetof_object_meta_content_encoding;
    size_t sizeof_body_window;
    size_t offsetof_body_window_expected_len;
    size_t offsetof_body_window_object_size;
    size_t sizeof_failure;
    size_t offsetof_failure_class;
    size_t offsetof_failure_kind;
    size_t offsetof_failure_request_id;
    size_t sizeof_outcome;
    size_t alignof_outcome;
    size_t offsetof_outcome_meta;
    size_t offsetof_outcome_body;
    size_t offsetof_outcome_failure;
    size_t offsetof_outcome_error;
} borink_layout;

/**
 * A failure, as the two numbers that describe every error of the core crate.
 *
 * `code` is a `borink_error_code`, and `detail` is the discriminant of the
 * value inside it. A `code` of 0 means that nothing failed. Both numbers are
 * append-only: a value defined today keeps its meaning.
 */
typedef struct borink_status {
    /**
     * The kind of failure, or 0 if there is none.
     */
    uint16_t code;
    /**
     * The discriminant of the value inside, or 0 if there is none.
     */
    uint16_t detail;
} borink_status;

/**
 * Bytes that your program owns and lends to a call.
 *
 * A `len` of 0 is an empty value, and `ptr` may then be null.
 *
 * # Lifetime
 *
 * The bytes must stay valid for the whole call. A value returned by a reading
 * call points into the storage that the call read, and is valid until you
 * release or reuse that storage.
 */
typedef struct borink_bytes {
    /**
     * The first byte.
     */
    const uint8_t *ptr;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_bytes;

/**
 * One container, and the token that opens it.
 *
 * Fill one in per client and keep it. Your program owns the three values, and
 * refreshing the token is assigning `token` again.
 *
 * # Lifetime
 *
 * The three values must stay valid for every call that takes this session.
 */
typedef struct borink_session {
    /**
     * The HTTP or HTTPS origin of the storage account.
     */
    struct borink_bytes endpoint;
    /**
     * The container name.
     */
    struct borink_bytes container;
    /**
     * The Entra ID bearer token, without the `Bearer ` prefix.
     */
    struct borink_bytes token;
} borink_session;

/**
 * A range of bytes, as an offset from the start of your request buffer.
 */
typedef struct borink_span {
    /**
     * The offset of the first byte.
     */
    size_t start;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_span;

/**
 * One request header, as two ranges of the request buffer.
 */
typedef struct borink_request_header {
    /**
     * The range that holds the header name.
     */
    struct borink_span name;
    /**
     * The range that holds the header value.
     */
    struct borink_span value;
} borink_request_header;

/**
 * A request head, as ranges of the buffer that holds it.
 */
typedef struct borink_request_head {
    /**
     * Whether the head was written, and what stopped it.
     *
     * A `code` of 0 means that the head is in your buffer.
     */
    struct borink_status status;
    /**
     * The number of bytes that this request head needs.
     *
     * This is the exact size whenever the plan is valid, whether or not the
     * head was written. Size one buffer by it and reuse that buffer.
     */
    size_t required;
    /**
     * The HTTP method, as a `borink_method`.
     */
    uint16_t method;
    /**
     * The range that holds the complete object URL.
     */
    struct borink_span url;
    /**
     * How many of `headers` this request uses.
     */
    size_t header_count;
    /**
     * The headers, in the order that the core crate wrote them.
     */
    struct borink_request_header headers[BORINK_MAX_HEADERS];
} borink_request_head;

/**
 * The byte range that a read requests.
 */
typedef struct borink_range {
    /**
     * Which form of range this is, as a `borink_range_form`.
     */
    uint16_t form;
    /**
     * The first byte, or the length of a suffix.
     */
    uint64_t start;
    /**
     * The byte after the last byte, for a bounded range.
     */
    uint64_t end;
} borink_range;

/**
 * The part of a read plan that holds no borrows.
 *
 * Store one of these while the request is in flight, and pass it to
 * `borink_accept_get_head` when the response arrives. It is the whole
 * per-request context: this crate keeps none of its own.
 */
typedef struct borink_get_shape {
    /**
     * Whether the read asks for bytes or for metadata, as a
     * `borink_get_kind`.
     */
    uint16_t kind;
    /**
     * The byte range that the read requests.
     */
    struct borink_range range;
    /**
     * The precondition that the read carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_get_shape;

/**
 * Storage that a call writes into.
 *
 * A `len` of 0 is an empty buffer, and `ptr` may then be null.
 */
typedef struct borink_bytes_mut {
    /**
     * The first byte.
     */
    uint8_t *ptr;
    /**
     * The number of bytes.
     */
    size_t len;
} borink_bytes_mut;

/**
 * The part of a write plan that holds no borrows.
 */
typedef struct borink_put_shape {
    /**
     * The precondition that the write carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_put_shape;

/**
 * The part of a removal plan that holds no borrows.
 */
typedef struct borink_delete_shape {
    /**
     * What the removal takes with it, as a `borink_delete_kind`.
     */
    uint16_t kind;
    /**
     * The precondition that the removal carries, as a `borink_condition`.
     */
    uint16_t condition;
} borink_delete_shape;

/**
 * A number that a response head may not carry.
 */
typedef struct borink_maybe_u64 {
    /**
     * Whether the head carried this number.
     */
    bool present;
    /**
     * The number.
     */
    uint64_t value;
} borink_maybe_u64;

/**
 * Bytes that a response head may not carry.
 *
 * `present` and an empty `bytes` are different facts. A header that the
 * service sent empty is present, and one it did not send is not.
 *
 * # Lifetime
 *
 * `bytes` points into the storage that the `borink_header_ref`s of the call
 * pointed into, or into the error body that you passed. It is valid until you
 * release or reuse that storage.
 */
typedef struct borink_maybe_bytes {
    /**
     * Whether the head carried this value.
     */
    bool present;
    /**
     * The bytes of it.
     */
    struct borink_bytes bytes;
} borink_maybe_bytes;

/**
 * Object metadata, borrowed from the response head.
 *
 * # Lifetime
 *
 * Every field points into the storage that the `borink_header_ref`s pointed
 * into, and is valid until you release or reuse it.
 */
typedef struct borink_object_meta {
    /**
     * The size of the whole object.
     */
    struct borink_maybe_u64 size;
    /**
     * The entity tag.
     */
    struct borink_maybe_bytes e_tag;
    /**
     * The value of the `Last-Modified` header.
     */
    struct borink_maybe_bytes last_modified;
    /**
     * The version identifier.
     */
    struct borink_maybe_bytes version;
    /**
     * The value of the `Content-Encoding` header.
     */
    struct borink_maybe_bytes content_encoding;
} borink_object_meta;

/**
 * Where the bytes of the response body belong in the object.
 */
typedef struct borink_body_window {
    /**
     * The offset in the object of the first byte of the response body.
     */
    uint64_t object_offset;
    /**
     * The exact length of the response body.
     */
    struct borink_maybe_u64 expected_len;
    /**
     * The size of the whole object.
     */
    struct borink_maybe_u64 object_size;
} borink_body_window;

/**
 * A response head that reports a failure.
 *
 * Store one of these and pass it back to `borink_finish_get_error_body` to
 * finish a `NeedErrorBody`.
 *
 * A `NotFound` fills `kind` alone. A missing object is not a failure of the
 * head: it names an error and carries no status and no category, so both are
 * 0.
 *
 * # Lifetime
 *
 * `request_id` points into the storage that the `borink_header_ref`s pointed
 * into. Copy it if you keep this value past that storage.
 */
typedef struct borink_failure {
    /**
     * The HTTP status code.
     */
    uint16_t status;
    /**
     * The category of the failure, as a `borink_failure_class`. Use it to
     * decide whether to retry.
     *
     * This is `class` in the core crate, which C++ cannot spell.
     */
    uint16_t class_;
    /**
     * The specific error that the head or the body named, as a
     * `borink_service_error`.
     */
    uint16_t kind;
    /**
     * The value of the `x-ms-request-id` header.
     */
    struct borink_maybe_bytes request_id;
} borink_failure;

/**
 * The result of reading one response head.
 *
 * One value describes a read, a write and a removal. The fields that the
 * operation does not fill are absent.
 *
 * # Lifetime
 *
 * Everything that this value borrows is valid until you release or reuse the
 * storage that the `borink_header_ref`s pointed into.
 */
typedef struct borink_outcome {
    /**
     * What to do with the response, as a `borink_disposition`.
     */
    uint16_t disposition;
    /**
     * The metadata from the head.
     */
    struct borink_object_meta meta;
    /**
     * Where the bytes of the body belong.
     */
    struct borink_body_window body;
    /**
     * The failure, for `NeedErrorBody`, `ServiceFailure` and `NotFound`.
     */
    struct borink_failure failure;
    /**
     * Why the call was refused, for `Invalid`.
     */
    struct borink_status error;
} borink_outcome;

/**
 * One response header, as the bytes that you already hold.
 *
 * Build a small array of these from wherever your HTTP library keeps the
 * head, and reuse the array. This crate copies none of it.
 *
 * # Lifetime
 *
 * Both values must stay valid for as long as you use the outcome that the
 * reading call returns.
 */
typedef struct borink_header_ref {
    /**
     * The header name. A name that is not text is ignored.
     */
    struct borink_bytes name;
    /**
     * The header value.
     */
    struct borink_bytes value;
} borink_header_ref;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Compares the layout a C compiler computed with the one this crate uses.
 *
 * Returns the number of fields of `probe` that differ, and 0 when every one
 * agrees. Call it once at startup, or from a static assertion in your own
 * test, before you read a field of any struct here.
 *
 * # Safety
 *
 * `probe` must be null or point at one readable `borink_layout`. A null
 * `probe` counts every field as different.
 */
size_t borink_layout_disagrees(const struct borink_layout *probe);

/**
 * Reports what is wrong with `session`, if anything.
 *
 * A `code` of 0 means that the session can build requests. Every other call
 * makes the same check, so this exists to fail early.
 *
 * # Safety
 *
 * `session` must be null or point at one readable `borink_session` whose
 * three values are each readable for their length.
 */
struct borink_status borink_validate(const struct borink_session *session);

/**
 * Writes the request head of a read into `buf`.
 *
 * Pass an empty `condition_value` if `shape` carries no condition. Pass an
 * empty `buf` to learn the size that this request needs.
 *
 * # Safety
 *
 * `session` and `shape` must each be null or point at one readable value.
 * `key`, `condition_value` and `buf` must each address their stated length,
 * and `buf` must be reached through nothing else during the call.
 */
struct borink_request_head borink_encode_get(const struct borink_session *session,
                                             const struct borink_get_shape *shape,
                                             struct borink_bytes key,
                                             struct borink_bytes condition_value,
                                             struct borink_bytes_mut buf,
                                             uint64_t unix_seconds);

/**
 * Writes the request head of a write into `buf`.
 *
 * The head states `content_len`. You send those bytes yourself.
 *
 * # Safety
 *
 * As `borink_encode_get`.
 */
struct borink_request_head borink_encode_put(const struct borink_session *session,
                                             const struct borink_put_shape *shape,
                                             struct borink_bytes key,
                                             struct borink_bytes condition_value,
                                             struct borink_bytes_mut buf,
                                             uint64_t content_len,
                                             uint64_t unix_seconds);

/**
 * Writes the request head of a removal into `buf`.
 *
 * # Safety
 *
 * As `borink_encode_get`.
 */
struct borink_request_head borink_encode_delete(const struct borink_session *session,
                                                const struct borink_delete_shape *shape,
                                                struct borink_bytes key,
                                                struct borink_bytes condition_value,
                                                struct borink_bytes_mut buf,
                                                uint64_t unix_seconds);

/**
 * Reads the response head of a read.
 *
 * Pass the same `shape` that you passed to `borink_encode_get`, and one
 * `borink_header_ref` per response header. The outcome points into the same
 * bytes as those headers.
 *
 * # Safety
 *
 * `session` and `shape` must each be null or point at one readable value.
 * `headers` must address `header_count` readable values.
 *
 * # Lifetime
 *
 * The bytes that `headers` points at must stay valid, and must not move, for
 * as long as you use the returned outcome.
 */
struct borink_outcome borink_accept_get_head(const struct borink_session *session,
                                             const struct borink_get_shape *shape,
                                             uint16_t status,
                                             const struct borink_header_ref *headers,
                                             size_t header_count);

/**
 * Reads the response head of a write.
 *
 * # Safety
 *
 * As `borink_accept_get_head`.
 *
 * # Lifetime
 *
 * As `borink_accept_get_head`.
 */
struct borink_outcome borink_accept_put_head(const struct borink_session *session,
                                             const struct borink_put_shape *shape,
                                             uint16_t status,
                                             const struct borink_header_ref *headers,
                                             size_t header_count);

/**
 * Reads the response head of a removal.
 *
 * # Safety
 *
 * As `borink_accept_get_head`.
 *
 * # Lifetime
 *
 * As `borink_accept_get_head`.
 */
struct borink_outcome borink_accept_delete_head(const struct borink_session *session,
                                                const struct borink_delete_shape *shape,
                                                uint16_t status,
                                                const struct borink_header_ref *headers,
                                                size_t header_count);

/**
 * Finishes a read whose head asked for the error body.
 *
 * Pass the `failure` of that outcome and the body that you read. Pass an
 * empty body if you read none: the outcome is then final with the error
 * unnamed.
 *
 * # Safety
 *
 * `session` and `failure` must each be null or point at one readable value.
 * `body` must address its stated length.
 *
 * # Lifetime
 *
 * `failure->request_id` must still point at valid bytes, and they must stay
 * valid for as long as you use the returned outcome. So must `body`.
 */
struct borink_outcome borink_finish_get_error_body(const struct borink_session *session,
                                                   const struct borink_failure *failure,
                                                   struct borink_bytes body);

/**
 * Finishes a write whose head asked for the error body.
 *
 * # Safety
 *
 * As `borink_finish_get_error_body`.
 *
 * # Lifetime
 *
 * As `borink_finish_get_error_body`.
 */
struct borink_outcome borink_finish_put_error_body(const struct borink_session *session,
                                                   const struct borink_failure *failure,
                                                   struct borink_bytes body);

/**
 * Finishes a removal whose head asked for the error body.
 *
 * # Safety
 *
 * As `borink_finish_get_error_body`.
 *
 * # Lifetime
 *
 * As `borink_finish_get_error_body`.
 */
struct borink_outcome borink_finish_delete_error_body(const struct borink_session *session,
                                                      const struct borink_failure *failure,
                                                      struct borink_bytes body);

/**
 * Writes one sentence naming what `outcome` says.
 *
 * Returns the length of the whole sentence, which may be longer than `into`.
 * The part that fits is written. A null `outcome` writes nothing and returns
 * 0.
 *
 * # Safety
 *
 * `outcome` must be null or point at one readable value whose borrowed fields
 * still address valid bytes. `into` must address its stated length and be
 * reached through nothing else during the call.
 */
size_t borink_describe(const struct borink_outcome *outcome, struct borink_bytes_mut into);

/**
 * Writes one sentence naming what `status` says.
 *
 * Returns the length of the whole sentence, exactly as `borink_describe`.
 *
 * # Safety
 *
 * `into` must address its stated length and be reached through nothing else
 * during the call.
 */
size_t borink_describe_status(struct borink_status status, struct borink_bytes_mut into);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BORINK_OBJECT_STORAGE_H */
